name = "Resample"
uuid = "318ae45f-2437-4276-8d16-19df99ea8507"
authors = ["Rik Huijzer <t.h.huijzer@rug.nl>"]
version = "1.0.0"

[deps]
NearestNeighbors = "b8a86587-4115-5ab1-83bc-aa920d37bbce"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"

[compat]
julia = "1.6"
