name = "Resample"
uuid = "318ae45f-2437-4276-8d16-19df99ea8507"
authors = ["Rik Huijzer <t.h.huijzer@rug.nl>"]
version = "0.1.0"

[deps]
NearestNeighbors = "b8a86587-4115-5ab1-83bc-aa920d37bbce"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"
